apiVersion: v1
kind: ServiceAccount
metadata:
  name: das
  namespace: gps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: das-job-runner
  namespace: gps
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: das-job-runner-binding
  namespace: gps
subjects:
  - kind: ServiceAccount
    name: das
roleRef:
  kind: Role
  name: das-job-runner
  apiGroup: rbac.authorization.k8s.io
